CREATE TABLE IF NOT EXISTS tasks (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  board_id INTEGER REFERENCES boards(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  status TEXT DEFAULT '',
  owners TEXT DEFAULT '[]',
  cal_start TEXT DEFAULT '',
  cal_end TEXT DEFAULT '',
  position INTEGER DEFAULT 0,
  stage TEXT DEFAULT 'backlog',
  category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS due_date TEXT DEFAULT '';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS priority TEXT DEFAULT 'none';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS recurrence TEXT DEFAULT '';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS subtasks TEXT DEFAULT '[]';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS assigned_to_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;
