CREATE TABLE IF NOT EXISTS board_members (
  id SERIAL PRIMARY KEY,
  board_id INTEGER REFERENCES boards(id) ON DELETE CASCADE,
  board_owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  member_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
