CREATE TABLE IF NOT EXISTS invites (
  id SERIAL PRIMARY KEY,
  token TEXT UNIQUE NOT NULL,
  inviter_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  invitee_email TEXT NOT NULL,
  board_id INTEGER REFERENCES boards(id) ON DELETE CASCADE,
  board_owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  used_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
